### ISSUE TITLE
Is this project safe to try?

### ISSUE THREAD

**Issue by bubenkoff** [FindHotel/auto-snapshot#8]
Hi
As I remember it was a pilot project but did it go further than that?

**Comment by germangh** [comment]
It is safe to use AFAIK. We did use it for a while and seemed to work fine. At the moment we have moved almost completely into spot instances and EFS so we don't need automated EBS snapshots anymore.

**Comment by germangh** [comment]
Hey @bubenkoff but actually I just remembered that this CF template that AWS posted some time ago seemed to be deprecating this repo:
https://aws.amazon.com/answers/infrastructure-management/ebs-snapshot-scheduler/

**Comment by bubenkoff** [comment]
ah that's cool, thanks for pointing it out!
